[package]
authors     = ["Xavier Lau <c.estlavie@icloud.com>"]
description = "subrpcer"
edition     = "2018"
homepage    = "https://subalfred.l2ust.world"
license     = "GPL-3.0"
name        = "subrpcer"
readme      = "README.md"
repository  = "https://github.com/l2ust/subalfred"
version     = "0.3.0"

[badges]
maintenance = { status = "actively-developed" }

[features]
raw-params = []
sender = [
	"isahc",
	"thiserror",
	"tracing",
]

[dependencies]
isahc         = { version = "1.4.0", optional = true, features = ["json"] }
serde         = { version = "1.0.127" }
serde_json    = { version = "1.0.66" }
subrpcer-impl = { version = "0.1.2" }
thiserror     = { version = "1.0.26", optional = true }
tracing       = { version = "0.1.26", optional = true }
