[package]
authors     = ["Xavier Lau <c.estlavie@icloud.com>"]
description = "subrpcer"
edition     = "2018"
homepage    = "https://subrpcer.l2ust.world/"
license     = "GPL-3.0"
name        = "subrpcer"
readme      = "README.md"
repository  = "https://github.com/l2ust/subrpcer/"
version     = "0.1.0"

[badges]
maintenance = { status = "actively-developed" }

[features]
raw-params = []
sender     = [
	"anyhow",
	"isahc",
	"tracing",
]

[dependencies]
anyhow     = { version = "1.0.35", optional = true }
isahc      = { version = "0.9.13", optional = true, features = ["json"] }
serde      = { version = "1.0.118" }
serde_json = { version = "1.0.60" }
tracing    = { version = "0.1.22", optional = true }
