[package]
authors     = ["Xavier Lau <c.estlavie@icloud.com>"]
description = "Your Substrate Alfred"
edition     = "2018"
homepage    = "https://subalfred.l2ust.world/"
license     = "GPL-3.0"
name        = "subalfred"
readme      = "README.md"
repository  = "https://github.com/l2ust/subalfred/"
version     = "0.1.0"

[[bin]]
name = "subalfred"
path = "src/main.rs"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
anyhow             = "1.0.36"
app_dirs2          = "2.3.1"
array-bytes        = { version = "0.3.0" }
async-std          = { version = "1.8.0", features = ["attributes"] }
base58             = "0.1.0"
clap               = "3.0.0-beta.2"
futures            = "0.3.8"
githuber           = { version = "0.1.0", path = "githuber" }
isahc              = { version = "0.9.14", features = ["json"] }
parity-scale-codec = "1.3.5"
pretty_env_logger  = "0.4.0"
regex              = "1.4.2"
serde              = "1.0.118"
serde_json         = "1.0.60"
serde_yaml         = "0.8.14"
subcryptor         = { version = "0.1.0", path = "subcryptor" }
subhasher          = { version = "0.1.0", path = "subhasher" }
submetadatan       = { version = "0.1.0", features = ["codec"], path = "submetadatan" }
subrpcer           = { version = "0.1.0", features = ["raw-params", "sender"], path = "subrpcer" }
tracing            = "0.1.22"

[workspace]
# TODO: move out, separate into a single crate
members = [
	"githuber",
	"subcryptor",
	"subhasher",
	"submetadatan",
	"subrpcer",
	"substorager",
]
