[package]
authors     = ["Xavier Lau <xavier@inv.cafe>"]
description = "Your Substrate Alfred"
edition     = "2021"
homepage    = "https://subalfred.hack.ink"
license     = "GPL-3.0"
name        = "subalfred"
readme      = "README.md"
repository  = "https://github.com/hack-ink/subalfred"
version     = "0.1.0"

[[bin]]
name = "subalfred"
path = "src/main.rs"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
# crates.io
anyhow    = { version = "1.0" }
async-std = { version = "1.10", features = ["attributes"] }
# hack-ink
cli      = { package = "subalfred-cli", version = "0.1.0", path = "src/cli" }
executor = { package = "subalfred-executor", version = "0.1.0", path = "src/executor" }

# [profile.release]
# lto = true

[workspace]
members = [
	"src/cli",
	"src/executor",
	"subcryptor",
	"subgrandpa",
	"subhasher",
	"submetadatan",
	"subrpcer",
	"subrpcer/impl",
	"substorager",
]
