[package]
authors     = ["Xavier Lau <c.estlavie@icloud.com>"]
description = "Your Substrate Alfred"
edition     = "2018"
homepage    = "https://subalfred.l2ust.world"
license     = "GPL-3.0"
name        = "subalfred"
readme      = "README.md"
repository  = "https://github.com/l2ust/subalfred"
version     = "0.1.0"

[[bin]]
name = "subalfred"
path = "src/main.rs"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
anyhow             = { version = "1.0.38" }
app_dirs2          = { version = "2.3.1" }
array-bytes        = { version = "0.3.0" }
async-std          = { version = "1.9.0", features = ["attributes"] }
base58             = { version = "0.1.0" }
clap               = { version = "3.0.0-beta.2" }
futures            = { version = "0.3.12" }
githuber           = { version = "0.2.1" }
isahc              = { version = "1.0.3", features = ["json"] }
parity-scale-codec = { version = "1.3.6" }
pretty_env_logger  = { version = "0.4.0" }
regex              = { version = "1.4.3" }
serde              = { version = "1.0.119" }
serde_json         = { version = "1.0.61" }
serde_yaml         = { version = "0.8.15" }
subcryptor         = { version = "0.1.1" }
subhasher          = { version = "0.1.1" }
submetadatan       = { version = "0.1.2", features = ["codec"] }
subrpcer           = { version = "0.1.3", features = ["raw-params", "sender"] }
tracing            = { version = "0.1.22" }

[workspace]
members = [
	"subcryptor",
	"subgrandpa",
	"subhasher",
	"submetadatan",
	"subrpcer",
	"substorager",
]

# Local Development
# [patch.crates-io]
# githuber     = { path = "../githuber" }
# subcryptor   = { path = "subcryptor" }
# subhasher    = { path = "subhasher" }
# submetadatan = { path = "submetadatan" }
# subrpcer     = { path = "subrpcer" }
