[package]
authors     = ["Xavier Lau <c.estlavie@icloud.com>"]
description = "Your Substrate Alfred"
edition     = "2018"
homepage    = "https://subalfred.l2ust.world/"
license     = "GPL-3.0"
name        = "subalfred"
readme      = "README.md"
repository  = "https://github.com/l2ust/subalfred/"
version     = "0.1.0"

[[bin]]
name = "subalfred"
path = "src/main.rs"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
anyhow            = { version = "1.0.34" }
app_dirs2         = { version = "2.3.1" }
array-bytes       = { version = "0.1.0", path = "array-bytes" }
async-std         = { version = "1.7.0", features = ["attributes"] }
base58            = { version = "0.1.0" }
blake2-rfc        = { version = "0.2.18" }
byteorder         = { version = "1.3.4" }
clap              = { version = "3.0.0-beta.2" }
futures           = { version = "0.3.8" }
githuber          = { version = "0.1.0", path = "githuber" }
isahc             = { version = "0.9.13", features = ["json"] }
pretty_env_logger = { version = "0.4.0" }
regex             = { version = "1.4.2" }
serde             = { version = "1.0.117" }
serde_json        = { version = "1.0.59" }
serde_yaml        = { version = "0.8.14" }
substrate-rpc-api = { version = "0.1.0", path = "substrate-rpc-api" }
toml              = { version = "0.5.7" }
tracing           = { version = "0.1.21" }
twox-hash         = { version = "1.6.0" }

[workspace]
# TODO: move out, separate into a single crate
members = [
	"array-bytes",
	"githuber",
	"substrate-rpc-api",
]
