[package]
authors     = ["Xavier Lau <hi@xavier.zone>"]
build       = "build.rs"
description = "Your Substrate Alfred"
edition     = "2018"
homepage    = "https://subalfred.l2ust.world"
license     = "GPL-3.0"
name        = "subalfred"
readme      = "README.md"
repository  = "https://github.com/l2ust/subalfred"
version     = "0.1.0"

[[bin]]
name = "subalfred"
path = "src/main.rs"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
anyhow             = { version = "1.0" }
app_dirs2          = { version = "2.3" }
array-bytes        = { version = "1.4" }
async-std          = { version = "1.10", features = ["attributes"] }
base58             = { version = "0.2" }
cargo_toml         = { version = "0.10" }
futures            = { version = "0.3" }
githuber           = { version = "0.3.0-alpha.1" }
isahc              = { version = "1.5", features = ["json"] }
parity-scale-codec = { version = "2.3" }
pretty_env_logger  = { version = "0.4" }
regex              = { version = "1.5" }
serde              = { version = "1.0" }
serde_json         = { version = "1.0" }
serde_yaml         = { version = "0.8" }
structopt          = { version = "0.3" }
subcryptor         = { version = "0.2" }
subhasher          = { version = "0.1" }
submetadatan       = { version = "0.5", features = ["codec", "simple"] }
subrpcer           = { version = "0.4", features = ["raw-params", "isahc-client"] }
tracing            = { version = "0.1" }
walkdir            = { version = "2.3" }

[build-dependencies]
vergen = { version = "5.1" }

[workspace]
members = [
	"subcryptor",
	"subgrandpa",
	"subhasher",
	"submetadatan",
	"subrpcer",
	"subrpcer/impl",
	"substorager",
]

# Local Development
# [patch.crates-io]
# githuber       = { path = "../githuber" }
# subcryptor    = { path = "subcryptor" }
# subgrandpa    = { path = "subgrandpa" }
# subhasher     = { path = "subhasher" }
# submetadatan  = { path = "submetadatan" }
# subrpcer      = { path = "subrpcer" }
# subrpcer-impl = { path = "subrpcer/impl" }
# substorager   = { path = "substorager" }
