[package]
authors     = ["Xavier Lau <c.estlavie@icloud.com>"]
description = "Your Substrate Alfred"
edition     = "2018"
homepage    = "https://l2ust.world/subalfred"
license     = "GPL-3.0"
name        = "subalfred"
readme      = "README.md"
repository  = "https://github.com/l2ust/subalfred/"
version     = "0.1.0"

[[bin]]
name = "subalfred"
path = "src/main.rs"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
app_dirs2         = { version = "2.3.0" }
async-std         = { version = "1.7.0", features = ["attributes"] }
clap              = { version = "3.0.0-beta.2" }
futures           = { version = "0.3.8" }
githubman         = { version = "0.1.0", path = "githubman" }
isahc             = { version = "0.9.12", features = ["json"] }
log               = { version = "0.4.11" }
pretty_env_logger = { version = "0.4.0" }
regex             = { version = "1.4.2" }
serde             = { version = "1.0.117" }
serde_json        = { version = "1.0.59" }
serde_yaml        = { version = "0.8.14" }
toml              = { version = "0.5.7" }

[workspace]
members = ["githubman"]
