[package]
authors     = ["Xavier Lau <c.estlavie@icloud.com>"]
description = "subhasher"
edition     = "2018"
homepage    = "https://subalfred.l2ust.world"
license     = "GPL-3.0"
name        = "subhasher"
readme      = "README.md"
repository  = "https://github.com/l2ust/subalfred"
version     = "0.1.2"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
blake2-rfc         = { version = "0.2.18" }
byteorder          = { version = "1.4.3" }
parity-scale-codec = { version = "2.1.1" }
twox-hash          = { version = "1.6.0" }
