[package]
authors     = ["Xavier Lau <c.estlavie@icloud.com>"]
description = "submetadatan"
edition     = "2018"
homepage    = "https://submetadatan.l2ust.world"
license     = "GPL-3.0"
name        = "submetadatan"
readme      = "README.md"
repository  = "https://github.com/l2ust/submetadatan"
version     = "0.1.4"

[badges]
maintenance = { status = "actively-developed" }

[features]
codec             = [
	"parity-scale-codec",
	"substorager/codec",
]
simplify-metadata = ["thiserror"]

[dependencies]
parity-scale-codec = { version = "2.0.0", optional = true, features = ["derive"] }
substorager        = { version = "0.1.3" }
thiserror          = { version = "1.0.23", optional = true }
